### PR TITLE
Remove needless malloc cast

### PR DESCRIPTION
**Pull request by mmcco**
Theo de Raadt recently committed this downstream in OpenBSD.

### CODE REVIEW

**Comment by fanf2** [comment]
Thanks for the suggestion, but although it is a good improvement for a purely C program, the cast is required in C++. Carsten Hey contributed some portability improvements in 2012 which included this cast, so that unifdef can be compiled with a C++ compiler (which is particularly helpful on Windows).

When investigating this history I discovered that unfortunately since 2012 there have been several regressions in C++ support. So I have made a different change which adds a missing cast elsewhere!

Thanks again for your contribution!

**Comment by rudimeier** [comment]
But this cast could hide serious compiler warnings. See
http://stackoverflow.com/questions/605845/do-i-cast-the-result-of-malloc

Maybe you can use something like this:

```C
s = CXXCAST(char*) malloc(size);
```
where
```C
#ifdef __cplusplus
# define CXXCAST(_type_)  (_type_)
#else
# define CXXCAST(_type_)
#fi
```

This would also tell the reader that you are doing this cast on purpose.

**Comment by fanf2** [comment]
Unifdef is not allowed to contain any #ifdef directives :-)

The main argument against casting malloc() is that it suppresses a type mismatch error if stdlib.h isn't included. But the cast doesn't suppress the warning about calling a function without a prototype, so that supposed problem isn't actually a problem in practice.

The other arguments are matters of style, and though I would normally agree with them, style has to take a second place to functionality.

**Comment by rudimeier** [comment]
On Friday 26 February 2016, Tony Finch wrote:
> Unifdef is not allowed to contain any #ifdef directives :-)

Hehe, forgot about your principles. I guess your abomination of #ifdef 
was the trigger why you've written your unifdef tool! ;)

**Comment by mmcco** [comment]
What's the benefit of supporting compilation with C++?

**Comment by fanf2** [comment]
Michael McConville <notifications@github.com> wrote:

> What's the benefit of supporting compilation with C++?

Microsoft's C compiler is crap.

Tony.
-- 
f.anthony.n.finch  <dot@dotat.at>  http://dotat.at/
Forties, Cromarty, Forth, Tyne, Dogger, Southwest Fisher: Variable 4. Slight
or moderate. Fair. Good.

**Pull request closed without merging**
